title:            Network Analysis of Dramatic Texts
description:      "Digital Humanities and Literary Studies"
logo:             logo.png
disqus_shortname: dlina
share:            true
dropcap:			       false
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  https://dlina.github.io

# Owner/author information
owner:
  name:           Frank Fischer, Mathias Göbel, Dario Kampkaspar, Peer Trilcke
  github:         dlina
  twitterhash:    DLINA
authors:
  mathias:
    name: Mathias Göbel
    display_name: Mathias
    email: goebel@sub.uni-goettingen.de
    web: http://mathias-goebel.github.io
    twitter: goebel_m
    github: mathias-goebel
    gravatar: 6cfefa5456ac7fd4f39298f29c05fae8
    description: Since more than 30 years Mathias plays this Real Life game with mixed results. After an inspiring lecture on 'Digital Humanities' he started combining statistics and literary studies, where he can use his close affinity to the computer and novice skills in writing scripts and programs to explore literary texts. Since then he tries to become familiar with &#35;!/bin/bash, the eXist-db and D3.js and server architecture in general.
  frank:
    name: Frank Fischer
    display_name: Frank
    gravatar: 0e4f5ff81e5b1b1976c939b57207bb2d
    email: ffischer@hse.ru
    web: https://www.hse.ru/en/org/persons/182492735
    twitter: umblaetterer
    github: lehkost
  peer:
    name: Peer Trilcke
    display_name: Peer
    gravatar: 3995a022afbaf45c8afdd0514d099e63
    email: trilcke@uni-potsdam.de
    web: http://www.peertrilcke.de
    twitter: peertrilcke
  dario:
    name: Dario Kampkaspar
    display_name: Dario
    email: kampkaspar@hab.de
    gravatar: fe3eb9abca16dcf4c80040b2011c3ce8
    github: dariok
  martin:
    name: Martin de la Iglesia
    display_name: Martin
    email: mdelaig@sub.uni-goettingen.de
    web: https://650centplague.wordpress.com/
    twitter: delaiglesia
    github: Martin-de-la-Iglesia
    gravatar: 910501447bef880e1352522362cb2852
  christopher:
    name: Christopher Kittel
    display_name: Chris
    email: contact@christopherkittel.eu
    twitter: chris_kittel
    github: chreman
  danil:
    name: Danil Skorinkin
    display_name: Danil
    email: dskorinkin@hse.ru
    twitter: DaniilSkorinkin
    github: danilsko
  german:
    name: German Palchikov
    display_name: German
    github: GermanGermanovich
    gravatar: 49117a44fc570a660ac40345fa667002
  cmil:
    name: Carsten Milling
    display_name: Carsten
    github: cmil
  ivan:
    name: Ivan Pozdniakov
    display_name: Ivan
    web: https://www.hse.ru/en/org/persons/137328113
    github: Pozdniakov
    gravatar: 3c7d6f076407e4c2ce3aaa6d515fe8cc

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Recent Posts
    url: /recent
  - title: Categories
    url: /categories
  - title: Linas
    url: /linas
  - title: Talks
    url: /talks
  - title: About
    url: /about


# Analytics and webmaster tools stuff goes here
#google_analytics:   UA-39365944-7
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: rouge
markdown:    kramdown
# paginate:    5
# paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '/_posts'
  siteurl: 'https://dlina.github.io'
  relativeLinks: 'http://dlina.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
